# ----
# Site

title: Donated Raffle for Streamlabs Chatbot
url: "https://bap14.github.io/Streamlabs_Chatbot"
baseurl: ""
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

repository: bap14/Streamlabs_DonatedRaffle
author:
  name: BleepBlamBleep
  email: bleepblambleep@gmail.com
  twitter: bleepblambleep
social:
  name: BleepBlamBleep
  links:
    - https://twitch.tv/bleepblambleep
    - https://github.com/bap14/Streamlabs_DonatedRaffle

# -----
# Build

timezone: America/New_York

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Instagram
  - Twitter
  - Twitch

types:
  - Document
  - Video

_comments:

data:
  footer:
    -
      social_icon: Twitter
      link: https://twitter.com/bleepblambleep
      name:
    -
      social_icon: Twitch
      link: https://twitch.tv/bleepblambleep
      name:
    -
      social_icon: Github
      link: https://github.com/bap14
      name: