title: Donated Raffle for Streamlabs Chatbot
theme: jekyll-theme-architect
description: > # this means to ignore newlines until "baseurl:"
  A custom script for Streamlabs Chatbot to run raffles that allow users to donate entries to others.
baseurl: "/Streamlabs_DonatedRaffle"
url: "https://bap14.github.io"
include: [_pages]
exclude: []
show_downloads: true
github:
  exe_url: "https://github.com/bap14/Streamlabs_DonatedRaffle/releases/download/v0.0.1.1/Streamlabs.Chatbot.Donated.Raffle.Setup-0.0.1.1.exe"
  zip_url: "https://github.com/bap14/Streamlabs_DonatedRaffle/releases/download/v0.0.1.1/Streamlabs.Chatbot.Donated.Raffle.Setup-0.0.1.1.zip"
