title: Donated Raffle for Streamlabs Chatbot
remote_theme: "daattali/beautiful-jekyll"
description: > # this means to ignore newlines until "baseurl:"
  A custom script for Streamlabs Chatbot to run raffles that allow users to donate entries to others.
baseurl: "/Streamlabs_DonatedRaffle"
url: "https://bap14.github.io"
navbar-links:
  Documentation:
    - Installation: "install"
    - Configuration: "configure"
    - Management: "management"
    - Examples: "examples"
navbar-col: "#f5f5f5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: BleepBlamBleep
social-network-links:
  rss: false
  email: "bleepblambleep@gmail.com"
  facebook: false
  github: false
  twitter: bleepblambleep
  twitch: bleepblambleep
  steam: bleepblambleep
share-links-active:
  twitter: true
  facebook: false
  google: false
  linkedin: false
timezone: "America/New_York"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
show_downloads: true
github:
  exe_url: "https://github.com/bap14/Streamlabs_DonatedRaffle/releases/download/v0.0.1.1/Streamlabs.Chatbot.Donated.Raffle.Setup-0.0.1.1.exe"
  zip_url: "https://github.com/bap14/Streamlabs_DonatedRaffle/releases/download/v0.0.1.1/Streamlabs.Chatbot.Donated.Raffle.Setup-0.0.1.1.zip"
